// (app)/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import { ConditionalLayout } from '@/components/ConditionalLayout';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Query_GPT💯 - Your AI Assistant",
  description: "Intelligent AI companion for instant answers, creative solutions, and deep insights",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";
// import Header from "@/components/Header";
// import { AppSidebar } from "@/components/app-sidebar";
// import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Query_GPT💯 - Your AI Assistant",
//   description: "Intelligent AI companion for instant answers, creative solutions, and deep insights",
// };

// export default function AppLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//       <html lang="en">
//         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//            <SidebarProvider>
//              <AppSidebar />
//                <SidebarInset>
//                   <Header />
//                </SidebarInset>
//             <div className="flex flex-col">
//               {children}
//             </div>
//            </SidebarProvider>
//         </body>
//       </html>
//   );
// }


// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "../globals.css";
// // import { ClerkProvider, SignedIn, SignedOut, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Query_gpt💯",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     // <ClerkProvider>
// //     //       <html lang="en">
// //     //   <body
// //     //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //     //   >
// //     //     {children}
// //     //   </body>
// //     // </html>
// //     // </ClerkProvider>
// //         <ClerkProvider>
// //       <html lang="en">
// //         <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
// //           {children}
// //         </body>
// //       </html>
// //     </ClerkProvider>
// //   );
// // }
